openapi: 3.0.0
info:
  title: VALIP VDM Item Master Writeback API
  description: API Description
  version: 1.0.0
  contact:
    name: OLiver Wilms
    email: oliver.wilms@va.gov
paths:
  /dispatch:
    summary: Get all the fields for the HDF entry using the class name and IEN as input parameters.
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
        required: true
      parameters:
        - in: query
          name: param
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VistaResponse'
          description: successful operation
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseStatus'
          description: Internal Server Error
      security:
        - basicAuth: []
components:
  schemas:
    responseStatus:
      type: object
      properties:
        statusCode:
          type: integer
        message:
          type: string
        errorCode:
          type: integer
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
